default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ShowMe2_development

test:
  <<: *default
  database: ShowMe2_test

production:
  <<: *default
  database: ShowMe2_production
  username: ShowMe2
  password: <%= ENV['SHOWME2_DATABASE_PASSWORD'] %>
